### PR TITLE
delete `--false-start --http2 --tlsv1.2`

### LINKED ISSUE #132: 官方脚本运行出错！！
脚本运行出错！
提示出下：
```
 curl -LROJ https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.               sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19253  100 19253    0     0  1446k      0 --:--:-- --:--:-- --:--:-- 1446k

 bash install-release.sh

info: Installing V2Ray v4.28.2 for x86_64
Downloading V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.28.2/v2ray-linux-64.zi               p
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   644  100   644    0     0   3425      0 --:--:-- --:--:-- --:--:--  3425
Downloading verification file for V2Ray archive: https://github.com/v2fly/v2ray-core/releases/download/v4.               28.2/v2ray-linux-64.zip.dgst
error: Check failed! Please check your network or try again.
removed: /tmp/tmp.h5Q5sNmkC8
```

已经有多人反馈这个问题。应该不是vps网络的原因。
我自己在vultr的debian10上也出现这个问题。

### PR DESCRIPTION
**Pull request by IceCodeNew**
Try to fix #132.
> `-q`: Disable .curlrc
> `-L`: Follow redirects
> `--false-start`: Enable TLS False Start
> `--http2`: Use HTTP 2
> `--tlsv1.2`: Use TLSv1.2 or greater

### CODE REVIEW

File: install-release.sh [hunk 1]
```diff
@@ -27,7 +27,9 @@ red=$(tput setaf 1)
 green=$(tput setaf 2)
 reset=$(tput sgr0)
 
-alias curl='"curl" --retry 5 --retry-delay 10 --retry-max-time 60 --false-start --http2 --tlsv1.2 -L'
+curl() {
+    $(type -P curl) -L -q -# --retry 5 --retry-delay 10 --retry-max-time 60 --false-start --http2 --tlsv1.2 "$@"
```
Comment (IceCodeNew) [inline install-release.sh:31]:
```suggestion
    $(type -P curl) -L -q --retry 5 --retry-delay 10 --retry-max-time 60 --false-start --http2 --tlsv1.2 "$@"
```
